### ISSUE TITLE
Saving graphs

### ISSUE THREAD

**Issue by cristim** [AutoSpotting/AutoSpotting#129]
# Github issue #

## Issue type ##

- Feature Idea

## Summary ##

Even though the savings can be seen at the end of the month in the Billing section of the AWS console, it may be nicer to also have some CloudWatch metrics with the achieved savings, updated in real-time.

## Expected results ##

Autospotting should create a few metrics which could be shown to Management:

- `HourlySavings`: absolute amount of money that the currently running spot instances are saving on a hourly basis compared to on-demand pricing (may be extended later to also cover reserved instances) 
- `HourlySavingsPercentage`: percentage of cost reduction versus on-demand capacity

**Comment by xlr-8** [comment]
That's a very interesting idea, I'm not that familiar with Cloudwatch custom metrics. How would you see the functioning of this feature?

My guess is that it would be something done via the Lambda scheduled call, where it would read the tagged ASG and report the difference/saving into Cloudwatch. Is that how you pictured it as well, or something different?

As usually that would be a feature to be turned on/off depending on the Lambda config - to avoid extra cost of the project - which would also vary depending on the frequency of the lambda call.

**Comment by cristim** [comment]
I was thinking to have it done on every normal run, sending the current hourly savings to those custom metrics. The function may need to be aware of the run frequency for some of those metrics, which would need to be handled somehow, maybe by changing the way we handle the CloudWatch event frequency stack parameter from the current expression to an absolute number, which we could pass to the function as another environment variable.

This definitely needs to be feature-flagged and off by default, because each custom metric costs $0.5/month and one of the design goals of AutoSpotting it so be as cheap as possible to run.

**Comment by otisg** [comment]
+1 for this, but making the output/destination configurable/pluggable, so one is not forced to send metrics to CloudWatch.

**Comment by xlr-8** [comment]
@otisg regarding the configurable option that I was thinking at first, would be an option, lets say `metric` that would indicate that metrics need to be gathered, and depending of its value (`cloudwatch`, `graphite`, `prometheus`, whatever) would call different methods to inject it.

However I have the feeling that the custom metric system could prove to be fairly tricky (handling host, ports, authentication, etc.) while relying on cloudwatch at first would be fairly simple as access/secret keys are the same, endpoint is already defined, etc.
We would then have generic method to get: saved cost per ASG, overall saved cost, timestamp, etc.

Now one way to bypass it, would be to define some sort of json format, in order to specify extra elements with at least the type (`cloudwatch`, `graphite`, etc) then each element could have other parameters (user, pass, host, etc). It would make this option more complex, but also more flexible. WDYT?

Otherwise, I was thinking of this issue tonight, and something came to my mind, if we want to implement it, then we would need to know the run frequency in order to estimate the save cost - wouldn't we?

Lets assume we run a spot m3.large ($0.05/h), vs t2.micro ($0.10/h) then the saved cost metric depends of the frequency:
* If we run every hour, then it would be: $0.05 saved at t
* If we run every half-hour, then it would be: $0.025 saved at t
* If we run every 5 min, then it would be: $0.00416 saved at t
* etc.

The other question is also what type of metrics do we put and what cloudwatch dimensions do we include?
In terms of metrics was thinking of at least:
* 1 metric per ASG - so gather all instance and make the math
* 1 general metric for all ASG used by autospotting in this region

In terms of dimension (we are limited to 10), I was thinking of at least:
* the name of the ASG
* the default type of instance in the ASG
* something else?

The namespace would logically be `autospotting` or something close.

ref:
https://docs.aws.amazon.com/sdk-for-go/api/service/cloudwatch/#PutMetricDataInput
https://docs.aws.amazon.com/sdk-for-go/api/service/cloudwatch/#CloudWatch.PutMetricData

**Comment by cristim** [comment]
Thanks for the detailed proposal. The frequency is given as parameter of the stack, we can also pass it to the function as an environment variable. We just need to get it parsed and used in the calculations

**Comment by cristim** [comment]
@xlr-8 we have it already as stack parameter, so we can just pass it to the Lambda function's env vars, which can just parse/handle it as-is.

There's no need to do a Describe call against the Cloudwatch Event Rule, which would also require some additional IAM permissions.

**Comment by xlr-8** [comment]
This would make more sense to be hosted in a dedicated project rather than here.

**Comment by gabegorelick** [comment]
The AWS Console now features a Spot Savings section: https://aws.amazon.com/about-aws/whats-new/2018/11/Amazon-EC2-Spot-Console-now-Provides-Access-to-Spot-Savings-Information/

This just counts all spot instances, so it would include any not launched by AutoSpotting. But it may be good enough.

> Even though the savings can be seen at the end of the month in the Billing section of the AWS console, it may be nicer to also have some CloudWatch metrics with the achieved savings, updated in real-time.

AWS Cost Explorer lets you see this daily now. So not sure how much value CloudWatch metrics would add.

**Comment by cristim** [comment]
> This just counts all spot instances, so it would include any not launched by AutoSpotting.

I guess it should allow you to specify tags which we could use for filtering only the instances launched by AutoSpotting.

If this is the case we could just document the procedure to filter based on our `launched-by-autospotting` tag key (or whatever key name we use).

**Comment by gabegorelick** [comment]
> I guess it should allow you to specify tags which we could use for filtering only the instances launched by AutoSpotting.

Unfortunately the Savings Summary available in the AWS Console under EC2 -> Spot Requests doesn't allow any type of interactive querying (no filtering, grouping, or anything). It just lists the number of spot instances you have, how long they've been running (in aggregate vCPU and GiB hours), and then the estimated savings based on said numbers. I'm pretty sure it doesn't even track savings from instances that no longer exist.

AWS Cost Explorer does allow this type of querying by tag (among a lot of other options). So you can query the money you've spent on EC2 instances with a certain set of tags. But you can't see how much you would have spent had the same number of instances been on-demand instances. So maybe there's value in AutoSpotting tracking this.

**Comment by cristim** [comment]
Got it, thanks!

We do have a figure logged on each run, should be easy to push it to a custom metric

**Comment by cristim** [comment]
I think the recently released savings dashboard pretty much solves this. https://www.reddit.com/r/aws/comments/jyf8ph/ec2_spot_console_now_shows_you_how_much_money/
