### ISSUE TITLE
Do not process AutoScaling groups while the CloudFormation stack that created them is in progress

### ISSUE THREAD

**Issue by runningman84** [AutoSpotting/AutoSpotting#13]
We use cfn init to publish a success signal. It would be cool if autospotting could read that and ensure that a replacement of an instance resulted in a successful deployment.

**Comment by cristim** [comment]
@runningman84 Thanks for your suggestion!

What would be the use case of this change, is it just to make sure the instances are added to the group immediately as soon as they are ready, before the grace period ended? Or would it be so that instances are not added at all if they are not ready? Do you usually take any kind of action based on this signal?

On my environments I only use the grace period to give the instances some time to set up and I assume they are ready to be added to the group as soon as that grace period is over, which as far as I can tell is the way AutoScaling is meant to be used. I understand why this is not optimal because it may lead to spinning conditions if the time is not enough or the new instance fails to setup, but from my experience it was good enough for most of my environments.

I'm not very familiar with cfn-init and cfn-signal so I have to figure out how could I integrate this in the current design. That's an event sent directly to your CloudFormation stack and I'm not sure if it's possible to intercept it and have it trigger my Lambda function.

I had a quick look at [this example] (http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-signal.html) and I see it's meant to be executed from the user-data script. I think an easy workaround may be to have your instances tag themselves with a custom temporary EC2 tag also at the end of the user-data script, and then invoke the Lambda function immediately, assuming they have the right permission from an IAM role to do all this.

The lambda function would be relatively easy to modify to check for the presence of that tag on the new spot instance, and add the instance immediately if the tag is there instead of waiting for the group's grace period. Once the new instance is added to the group the tag could be deleted since it's no longer needed, so that it doesn't consume one your only 10 available instance tags.

What do you think about this approach?

**Comment by cristim** [comment]
In the initial version I actually had the lambda function triggered by an SNS topic but I removed that to reduce complexity once I could just use a local CloudWatch event.

I think it makes sense to add it back for such use cases, just that with the currently implemented logic autospotting would still ignore that instance while it is still in its grace period so this execution would be in vain.

As I explained above the instance could tag itself from the user-data script with a predefined tag to report itself ready, and then AutoSpotting could be changed to ignore the grace period when that tag is present.

I am just not sure how serious is this issue, what impact does it have and if what do we gain for doing it worths the development effort.

But if it is critical enough for someone out there to spend time and implement it end-to-end and send a PR, I would be willing to accept it.

**Comment by xbglowx** [comment]
I am currently hitting a problem where cloudformation is doing a rolling upgrade of instances in na ASG while autospotting is trying to replace them. The cfn-signal never makes it back to cloudformation, letting it know to move onto the next instance, since the instance gets rebuilt as a spot before the signal could be sent.

I see two improvements here:

1. Don't let autospotting operate on an ASG that is currently being worked on by Cloudformation
1. Use EC2 tags to let autospotting know when it is safe to move onto the next instance in the ASG, similar to what cfn-signal is to Cloudformation.

**Comment by cristim** [comment]
@xbglowx You can also just disable autospotting while performing the Cloudformation stack update, by setting the spot-enabled tag to false.

**Comment by xbglowx** [comment]
This is true, but that would involve three code deployments, I think, which doesn't feel real right to me.

1. Set flag to false on all possibly affected ASGs
1. Deploy cloudformation changes 
1. Revert flag back to true on ASGs. 

Messing with the ASG flag is also prone to be forgotten by the operator.

Would be cleaner to make the software more aware of any on going changes to ASGs that were not triggered by itself, if that is even possible.

**Comment by cristim** [comment]
That's true, but I don't know if CloudFormation leaves any trace when it's doing changes against the ASGs.

**Comment by cristim** [comment]
One way to avoid touching the groups during CloudFormation stack updates is to query the status of its CloudFormtation stack, which we can get from the `aws:cloudformation:stack-name` tag set on the groups that are created by CloudFormation.

If the CloudFormation stack is in progress, we can just skip that group in the current run.

**Comment by mello7tre** [comment]
I am adding that feature, in days will open a new PR.
(it's already working, need only to add tests)

**Comment by cristim** [comment]
@mello7tre  great to hear that!

Please feel free to create a draft PR even earlier, so se can discuss on the code as early as possible.

**Comment by runningman84** [comment]
Btw. we switched to the new mixed instances autoscaling group feature and therefore do not use Autospot anymore.

**Comment by mello7tre** [comment]
but using mixed instance how are you able to fallback to ondemand if a spot instance fail to run ?
Reading aws documentation, there is no fallback to ondemand.

I made some tests, and can state that when using a mixed config, if a spot instance fail to launch it's NOT launched, as replacement, an ondemand one.
So i think that Autospotting solution is far better.

**Comment by cristim** [comment]
@mello7tre that's exactly what we also noticed when we tested the AutoScaling mixed spot implementation. We raised a support case and requested this feature about three months ago but it didn't land yet. 

At least with AutoSpotting one could take the matter into their own hands and fix it if it's really a dealbreaker.
