### ISSUE TITLE
In some cases AutoSpotting may fail to launch any spot instances

### ISSUE THREAD

**Issue by cristim** [AutoSpotting/AutoSpotting#147]
# Github issue #

## Issue type ##

- Bug

## Summary ##

At the moment the availability zone where we attempt to launch the next spot instance for a given group is chosen arbitrarily, simply by picking it from the first on-demand instance found in the group.

Because the list of instances from a group may be returned in the same order between multiple API calls(this may or may not be deterministic, TBD), the algorithm may fail to launch spot instances multiple times in a row, when that availability zone happens to have no spot prices lower than the on-demand price.

## Steps to reproduce ##

Create a group with two instances with a t2.micro instance type which is likely quite hard to beat by the spot market prices, but verify that at least one of the availability zones has a good spot price while the other doesn't have any.

Enable AutoSpotting on the group and notice if it can replace the instances.

## Expected results ##

AutoSpotting replaces one of the instances with spot, and fails for the other one until the market price gets low enough for at least one instance type.

## Actual results ##

Sometimes AutoSpotting will fail to launch any spot instances, because it always attempts to replace the on-demand instance where there is no cheaper available spot instance.

As a solution the selected on-demand instance would be picked up randomly, or even better would be picked from the best priced availability zone where we are guaranteed to be able to launch a spot instance.

This is likely the behavior observed in #146.

**Comment by xlr-8** [comment]
I think picking it up randomely might however be safer, as we have some restriction about the number of instances spawned within an AZ. So picking always the AZ with the lower price, might result in weird behavior where autospotting would stop processing as well.

Don't you think? If you're fine with that, I'll work on the random selection.

**Comment by cristim** [comment]
I like the idea of random selection as well

**Comment by xlr-8** [comment]
I haven't re-tested this but re-reading this issue, it's kinda surprising due to https://github.com/cristim/autospotting/pull/73.

I'm saying this because on the fetching of an ondemand instance [here](https://github.com/cristim/autospotting/blob/master/core/autoscaling.go#L319-L333), we can see that the data is fetched from the [getInstance method](https://github.com/cristim/autospotting/blob/master/core/autoscaling.go#L464-L470) which itself gets it from the map in [instance.go](https://github.com/cristim/autospotting/blob/master/core/instance.go#L84) or the map iteration is already not supposed to be predictable according to [their blog](https://blog.golang.org/go-maps-in-action):
> Iteration order
>
> When iterating over a map with a range loop, the iteration order is not specified and is not guaranteed to be the same from one iteration to the next. Since Go 1 the runtime randomizes map iteration order, as programmers relied on the stable iteration order of the previous implementation.

So some extra randomisation could be added, but I'm not sure of the added value of it.

**Comment by xlr-8** [comment]
Making [a small modification](https://gist.github.com/xlr-8/3a164655b43d65b1b4b010583ba0b5da) on the test sort of confirms the thoughts:

```bash
> for i in {1..10}; do echo "Run $i on 10"; go test -v ./core/... | grep Found; echo "";done
Run 1 on 10
Found: 1b
Found: 1c

Run 2 on 10
Found: 1b
Found: 1e

Run 3 on 10
Found: 1b
Found: 1c

Run 4 on 10
Found: 1b
Found: 1c

Run 5 on 10
Found: 1b
Found: 1d

Run 6 on 10
Found: 1b
Found: 1c

Run 7 on 10
Found: 1b
Found: 1b

Run 8 on 10
Found: 1b
Found: 1f

Run 9 on 10
Found: 1b
Found: 1c

Run 10 on 10
Found: 1b
Found: 1c
```

Some seem indeed more selected than other, but it's not always the same that are being picked. Also reading at [this code](https://github.com/cristim/autospotting/blob/master/core/autoscaling.go#L472), I believe that should be a `return retI` rather than continuing iterating until the end, it doesn't seem to make quite sense.

**Comment by manfredlift** [comment]
Any updates on this? We frequently encounter this issue for `p3.2xlarge` instances.

**Comment by cristim** [comment]
@xlr-8 do you think we should close this issue?

**Comment by cristim** [comment]
This should no longer happen in the recent version that has event-based replacement logic.
