### ISSUE TITLE
Launch/replacement cycle efficiency improvements

### ISSUE THREAD

**Issue by otterley** [AutoSpotting/AutoSpotting#284]
Thanks for Autospotting!  Great work so far.

I recently enabled it for the first time in one of our Auto Scaling Groups, and I'm noticing that it's only launching 1 spot instance every 15 minutes.  This appears to be caused by the following factors:

1. The Health Check Grace Period configured on our ASG is 300 seconds, which is exactly the same as the Lambda execution frequency.  When the function is next executed after a Spot Instance is launched, the uptime of the instance is often *just under* 300 seconds, so we must wait yet again for the function to run.  So effectively it's a 10 minute grace period instead of a 5 minute grace period.  This can be remedied by the user by adjusting the Lambda execution frequency or by adjusting the Health Check Grace Period.

2. When the replacement Spot Instance has been deemed healthy (i.e., its uptime exceeds the grace period), the instance is added to the Auto Scaling Group, but the Lambda function appears not to attempt to launch a new Spot Instance until the next run, even though it probably could.  Is there a particular reason for that?

Additionally, I'm noticing that no matter how large the existing Auto Scaling Group is, only 1 Spot Instance is requested at a time.  Is there a reason for that as well?   Any objections to, say, making Autospotting more efficient by declaring a maximum ratio or absolute value of Spot Instances to launch simultaneously?

**Comment by cristim** [comment]
Thanks for reporting this.

Mainly for simplicity and stability reasons the current implementation only handles a single action per run on any given group. This may be slower than expected for the initial run but considering that Autospotting is designed towards usage against long-running groups, the added costs of this slow ramp-up is negligible.

Multiple actions may be doable but would need a bit of refactoring and need to be carefully orchestrated in order to minimize the risk of downtime to the group.

If you are interested to contribute this functionality I would like to see an implementation proposal in a pull request.

**Comment by cristim** [comment]
My main concern is that the grace period is arbitrary and may not guarantee that the instance is ready to receive traffic. In case it isn't, the group will notice and replace it quickly enough and without much impact.

If we do this for many instances at once, we risk replacing too many nodes with unhealthy spot instances, causing downtime.

When replacing more instances, it's also more likely to impact the metrics that trigger autoscaling policies, inadvertently terminating more instances than normally  expected.

I would be open to have this behavior optional and configurable, but keep the current as default.

**Comment by otterley** [comment]
The grace period is tunable by the user, so it can always be increased to suit the particular application.  

With ordinary Auto Scaling Groups, we don't use grace periods anyway -- we use Launch Lifecycle Hooks to signal readiness.  For example, we have a Step Function that is triggered by an instance launch that waits for an instance to join an ECS cluster and optionally starts a task before completing the Lifecycle Hook.  This transitions the newly-launched instance from `Pending:Wait` state to `InService` state.  If a timeout is reached, the Step Function sends an `ABANDON` signal to the same Hook, which makes the Auto Scaler terminate the faulty instance and possibly replace it.

I don't think we can use Launch Lifecycle Hooks with Autospotting, which is a shame.  As a replacement, I'd recommend implementors do something similar, except condition the execution of the health poller Step Function on the launch of the Spot Instance using CloudWatch Events.  Then, the poller can tag the instance when the instance is ready to attach to the Auto Scaling Group.

So, along with this change, I can also include functionality that would optionally make Autospotting attach the newly-launched Spot Instance to the Auto Scaling Group only if some sort of "healthy" tag is set on the instance. 

What do you think?

**Comment by cristim** [comment]
The main differentiator design principle of AutoSpotting is about minimizing the required configuration of the existing group, so that it can be rolled out at scale. If we require configuration changes, our users might as well switch to spot fleets or other tools that rely on such configuration changes and may have other benefits.

Hopefully the group should keep running as before, just with spot instances.

So I would like to avoid a requirement for the use of lifecycle hooks or custom user data scripts, but at the same time we should not break them if already configured, if this is the case then it's a bug that needs to be fixed if possible.

If some of these draining mechanisms can be implemented in Autospotting without breaking the lifecycle hooks, I would be glad to see it done.

**Comment by otterley** [comment]
> I would like to avoid a requirement for the use of lifecycle hooks or custom user data scripts, but at the same time we should not break them if already configured, if this is the case then it's a bug that needs to be fixed if possible.

I'm sorry to say that Lifecycle Hooks are already broken.  Half of this -- the termination Lifecycle Hook case -- will be fixed when #248 is merged (hopefully soon!).  The other half -- the launch Lifecycle Hook case -- cannot be addressed by Autospotting alone.   We're less concerned about Launch Lifecycle hooks, since health checks can always be made to fail later (via ELB health checks, or custom health reporters; see [here](https://docs.aws.amazon.com/autoscaling/ec2/userguide/healthcheck.html) for more details).

Lifecycle Hooks are solely a property of EC2 Auto Scaling Groups.  They apply only to instances that are launched and terminated by the EC2 Auto Scaler itself.  So, you can't declare Lifecycle Hooks on a Spot Instance.  You can't declare them on a Spot Fleet, either (so you don't have to worry about a mass exodus of users to Spot Fleets).   

When you add a standalone Spot Instance to an Auto Scaling Group, the new instance inherits the Group's Lifecycle Hooks, so that's good news -- but by then the launch has already completed, so the instance will go straight into `InService` state instead of `Pending:Wait` as with instances launched by the Auto Scaler itself.

Anyway, all I'm advocating here is an option to specify a tag that could be used as an indicia of health for Autospotting.  I wouldn't make it a requirement, and it only applies to launches, not terminations.

**Comment by xlr-8** [comment]
@otterley I haven't played that much with lifecycle hooks in ASG, however my understanding of AWS doc [1] is that they can be done via Cloudwatch (among others), which is also something Lambda could be triggered from [2].

Regarding the change of state from `InService` instead of `Pending:Wait` couldn't this be done by a lifecycle hook directly located in the user-data or so?

[1] https://docs.aws.amazon.com/autoscaling/ec2/userguide/lifecycle-hooks.html
[2] https://docs.aws.amazon.com/lambda/latest/dg/invoking-lambda-function.html

**Comment by cristim** [comment]
For anyone brave enough to be a guinea pig for barely tested code, the latest build from the #354 branch should mitigate this issue for new ASGs.

To install it just click on this URL:
https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/create/template?stackName=AutoSpotting&templateURL=https://s3.amazonaws.com/cloudprowess/custom/template_build_1439509.yaml

Please report back if you notice any issues.

**Comment by cristim** [comment]
The recently merged event-based execution mode should address this problem for new groups.

Closing this issue.
