### ISSUE TITLE
AutoSpotTerminateEvent enters CREATE_FAILED outside us-east-1

### ISSUE THREAD

**Issue by iainelder** [AutoSpotting/AutoSpotting#331]
# Github issue #

AutoSpotting is failing to create all its components in my AWS account.

The "delegate" AutoSpotTerminationEvent stack fails to create in all regions apart from us-east-1.

Our active region is us-west-2, so I really need AutoSpotting to work there.

## Issue type ##

- Bug Report

## Build number #

```
nightly-1010
```

## Configuration ##

To install AutoSpotting, I used the command from the [Getting Started] guide.

[Getting Started]: https://github.com/AutoSpotting/AutoSpotting/blob/master/START.md

The added profile and region parameters are the only difference.

```
aws cloudformation create-stack \
--stack-name AutoSpotting \
--template-url https://s3.amazonaws.com/cloudprowess/nightly/template.yaml \
--capabilities CAPABILITY_IAM \
--profile dev \
--region us-east-1
```

## Environment ##

- AWS region: all except us-east-1
- Type of environment: DefaultVPC
- Anonymized launch configuration: Not applicable

## Steps to reproduce ##

I ran the command in the Configuration section to install AutoSpotting.

I waited a few minutes for all the stacks to finish creating.

Then I checked the events of the AutoSpotTerminationEvent stack in us-west-2 to reveal the error message.

## Expected results ##

That the AutoSpotTerminationEvent stacks in all regions would enter the CREATE_COMPLETE state.

## Actual results ##

In all regions outside us-east-1, the AutoSpotTerminationEvent stack enters the CREATE_FAILED state.

The LambdaPermissionAutoSpotTerminationNotificationTopic resource gives an error like this:

```
Functions from 'us-east-1' are not reachable in this region ('us-west-2') (Service: AWSLambda; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: 100e219e-4a63-11e9-a748-ef5a0e264c08)
```

**Comment by cristim** [comment]
Thanks for reporting this. I've been aware of this for a few days and I'm already working on a fix.

I'm just struggling a bit with the complexity recently introduced in our CloudFormation template code in order to support this feature. So I'd like to first tackle this to make the CloudFormaiton stack more maintainable(hopefully some parts of this will also be reusable from Terraform) and then address the issue at hand. To paraphrase someone "if you have 5 hours to chop down a tree, spend the first 4 sharpening your saw" ;-)

**Comment by iainelder** [comment]
Just out of interest, why is the delegate stack AutoSpotTerminationEvent required?

**Comment by cristim** [comment]
The termination events are regional and need to be captured in each region.

Then we need to invoke the main Autospotting Lambda function which runs in a single region.

The problem is the events can't trigger a Lambda function from a different region.

My idea so far is to create a regional Lambda function that would be triggered by the event and then it should be able to call the main Lambda function.

**Comment by iainelder** [comment]
Have you considered using [StackSets](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-concepts.html)?

That might avoid the problem of communication across regions, and of splitting the solution into multiple stacks.

With that, an instance of the main AutoSpotting stack could be automatically installed in each region, and that stack would include the resources of the AutoSpotTerminationEvent stack.

I understand the main function is stateless, so there should be no problem with having several instances running as long as they each operate on a distinct region. The different instances of the main function wouldn't have to know about each other.

The events would have only to communicate with the main Lambda function in the same region. 

I suppose that would imply a big change (a simplification?) of the core lambda function, and it would of course split the logging across regions.

The split logging might be a disadvantange in some cases, but if it simplified the implementation it might be worth it.

(Forgive me if I'm way off track here. I don't understand very well the internals. But I'm just throwing out ideas about how to best take advantage of what CloudFormation already provides.)

**Comment by iainelder** [comment]
> an instance of the main AutoSpotting stack could be automatically installed in each region,

One problem. It requires hosting the AutoSpotting binary in all regions.

If that infrastructure could be provided by this project, it could be done using cross-region replication from the main S3 bucket.

Otherwise, then a scripted solution to set it up in each user account would probably be necessary.

**Comment by cristim** [comment]
Exactly, I didn't want to maintain buckets in all the regions, and also the unified logging makes it easier for me to test.

But users can store the binaries in their own buckets in any region they have infrastructure in and deploy it there and only restrict it to the current region. This is a relatively simple solution.

But I already have a fix for the current architecture, I just added a regional Lambda function that can call the global Lambda function using the Lambda invocation API.

It seemed to work when I tested it but I would like to have it a bit better tested since I changed the Cloudformation stack significantly in the process of doing it

**Comment by mello7tre** [comment]
AWS and CloudFormation do support cross-region sns subscription but need a separate Subscription CloudFormation Resource.
Currently Autospotting is creating the subscription directly in the Topic resource using the Subscription parameter, that way is not possible to specify the region.
====
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html?shortFooter=true#cfn-sns-subscription-region

**Comment by cristim** [comment]
Thanks @mello7tre I wasn't aware of this but I will definitely check it out.

**Comment by cristim** [comment]
@mello7tre if I read that correctly it means the topic has to be in the other region from the current stack.
I think what we need instead is that the Lambda function is in another region, unless we do this from the stack where we have the Lambda, but then we need to be aware of all the topics from the central stack that creates the main Lambda function.

The current implementation in #334 has the regional stacks aware of the main Lambda function ARN, but that's all we need to pass around

**Comment by cristim** [comment]
@iainelder, @mello7tre, please have a look at #334 and let me know if you have any concerns. Also it would be great if you could test it on your side. I'm also in the process of testing it but any help would be welcome.

**Comment by mello7tre** [comment]
You are right.

I have looked at the draft PR.
If i understand correctly the logic, you are creating another lambda that, when invoked, trigger the main one.
That other lambda is created in every configured region, so that the sns regional topic trigger it.
This way you circumvent the problem of the cross region between sns and lambda.

I have investigated some more the problem with the current template/logic.
The source of the problem is not the subscription but the lambda permission:
 LambdaPermissionAutoSpotTerminationNotificationTopic

We cannot create assign a lambda permission to a lambda in a region different from the one in which we are creating the stack.

Here the relative CF events log
```
14 Feb 2019 11:03:11 | LambdaPermissionAutoSpotTerminationNotificationTopic | CREATE_FAILED | Functions  from 'eu-west-1' are not reachable in this region ('us-east-1')  (Service: AWSLambda; Status Code: 404; Error Code:  ResourceNotFoundException; Request ID:  1e5b7762-3048-11e9-9b4f-5f6a9ddd5833)
```

We can continue using the current template if we relax a little the lambda permission and create it in the main CloudFormation stack (in the same one in which we create the main lambda)
this way:
```
    "LambdaPermissionAutoSpotTerminationNotificationTopic": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "Action": "lambda:InvokeFunction",
        "FunctionName": {
          "Ref": "LambdaFunction"
        },
        "Principal": "sns.amazonaws.com",
        "SourceArn": {
          "Fn::Sub": "arn:aws:sns::${AWS::AccountId}:AutoSpotTerminationEvent-AutoSpotTerminationNotificationTopic-*"
        }
      }
    }
```

We give main lambda permission to be invoked by any sns topic of your account in any region if the topic arn name begin with  AutoSpotTerminationEvent-AutoSpotTerminationNotificationTopic-.

If we can afford that more relaxed permission, i think this is the simpler way.
(i have not tested it, but it should work, (i have tested it using aws cli and that SourceArn format is supported, and permission is assigned successfully, so it should work via CF too))

**Comment by cristim** [comment]
Thanks, I'll try to simplify it further if this works

**Comment by mello7tre** [comment]
Sometimes i hate AWS!
Using `"arn:aws:sns::${AWS::AccountId}:AutoSpotTerminationEvent-AutoSpotTerminationNotificationTopic-*"` for SourceArn create successfully permissions, and you can see them in lambda web UI too, but if i publish a message to the Topic it does not work!

Debugging Topic, configuring "Delivery status logging", show an error about Topic not having permission to invoke lambda!

Even relaxing further the permission and configuring SourceAccount instead of SourceArn, so giving all account's topics permission to invoke the lambda, do not work.
Seems that Lambda need a specific resource arn when given permission to an sns topic and you cannot use a wildcard generic one.

So, i think you draft PR is, currently, the only solution to invoke a lambda cross region (but i have not tested it, need more time).

Just one note, in that case we can remove the sns section.
We can simply have:
`CloudWatch event (region localized)-> lambda (region localized) -> Main Lambda (in single region)`

But to make it work, keeping a "future compatibility" with sns triggering, should be better to "encapsulate" the event in a structure similar to a sns Message; this way main autospotting.go code do not need changes.

**Comment by mello7tre** [comment]
just for confirmation:
found an hidden AWS info that confirm observed behavior:
https://docs.aws.amazon.com/lambda/latest/dg/with-sns-example.html?shortFooter=true#with-sns-create-x-account-permissions
```
Do not use the --source-account parameter to add a source account to the Lambda policy when adding the policy. Source account is not supported for Amazon SNS event sources and will result in access being denied. 
```
