### ISSUE TITLE
Incorrect determination of instance profile of launch configuration

### ISSUE THREAD

**Issue by timboven** [AutoSpotting/AutoSpotting#355]
# Github issue #

## Issue type ##

- Bug Report
## Build number #

Current (master)

## Summary ##
The AWS API documents clearly that the value "IamInstanceProfile" returned from a Launch Configuration could be either the name or the ARN of the launch configuration (this depending on how it was created -- docs: https://github.com/AutoSpotting/AutoSpotting/blob/master/core/instance.go#L589). The code however assumes that it always returns the name of the Launch Configuration: https://github.com/AutoSpotting/AutoSpotting/blob/master/core/instance.go#L589

## Steps to reproduce ##

* Create a launch configuration where you reference the used iam instance profile by ARN
* Let autospotting do its thing

## Expected results ##

autospotting should replace the EC2's in the ASG created with this launch configuration

## Actual results ##

autospotting fails to create a spot instance due to an InvalidParameterValue as it is using the ARN of the launch configuration instead of the name of the Launch configuration

**Comment by cristim** [comment]
Thanks for reporting this.

This is a relatively new issue, we've been historically taking this from a running instance, where it was always available by ARN. I recently changed the logic to take it from the LC in order to be able to replace running instances started from an older LC that weren't replaced and may be drifting from the current LC. 

Apparently the LC is more flexible and can have this sometimes passed by name. It's definitely possible to describe the IAM Instance Profile when given by name and always get it passed by ARN to the running spot instance. 

Unfortunately I'm currently working on a large refactoring (#354) so this fix may take a few more weeks. But feel free to use an older build or preferably send a PR that fixes this issue properly.

**Comment by timboven** [comment]
@cristim I created PR #356 that solves this for me -- I compiled it and deployed my custom build in my test environment and none of these errors occur anymore.

Could you review my suggested change for fixing the issue?
