### ISSUE TITLE
Up-to-date Docker image on hub?

### ISSUE THREAD

**Issue by ps-jay** [AutoSpotting/AutoSpotting#370]
Hey there,

I do something off-the-happy path: I run autospotting as an ECS task, rather than a Lambda - because I have an ECS cluster sitting there with spare capacity.

The published Docker image is ~ 1 year old: https://hub.docker.com/r/cristim/autospotting/tags

Could this be updated?

Thanks!,
  Phil

**Comment by cristim** [comment]
The repo was since renamed, the current image is available at
https://hub.docker.com/repository/docker/autospotting/autospotting

The latest image is about three days old.

Just keep in mind that the Docker image is not supported and likely not feature-complete as the code might depend on some resources usually deployed from the standard CloudFormation stack.
