### ISSUE TITLE
Hybrid-instance-type

### ISSUE THREAD

**Issue by umitseremet** [AutoSpotting/AutoSpotting#420]
# Github issue #

## Issue type ##

- Feature Idea

## Build number #

```

```

## Configuration ##

I want to ask;
Although I have defined a couple of instance types for spot usage it usually chooses 1 of them, probably the cheapest one, but the same type usage is a risk because when an outage occurs all spots can be affected. Instead of "usually choosing the cheapest" strategy could we set a hybrid structure? If I define 4 instance types and there are 4 spots on the same zone, all instances can be different instance types. I am aware of that using different zone is redundancy but also using a hybrid structure is also a redundancy in the same region and it will contribute to the SLA. BTW, if there is a way I do not know to provide this could you share it with me?

## Actual results ##

```text
```

**Comment by cristim** [comment]
Thanks for your suggestion, this is a well known issue but in practice it's not as bad as it sounds.

Spot instances no longer terminate all at once when outbid, they will be gradually terminated as the spot capacity drops.

When this happens, you're usually able to still launch an on-demand instance in that AZ(unless we're also dealing with an ICE), which will be left running before we can replace it with something else. When we evaluate the replacement instance types, we actually iterate over all instance types allowed by the configuration, so if the initial spot instance type is no longer available we fallback to the next one and so on until we're able to launch something. So at the end of the day the current implementation gives you this sort of hybrid instance type configuration but it is only triggered by situations when the existing capacity is lost.

The real problem is that this is may happen right before an ICE event, so the group might fail to launch on-demand instances and then we're having an outage.

I have some plans on how to address this situation but it's not there yet. But if you're passionate about this enough to contribute a fix, I can elaborate further.

**Comment by waynerobinson** [comment]
That definitely sounds like it would deal with that situation.

Do you know if there's any documentation on the "spot instances no longer terminate all at once when outbid, they will be gradually terminated as the spot capacity drops." though? I haven't been able to locate it anyway in AWS' docs. 🙁

**Comment by cristim** [comment]
See this blog post: https://aws.amazon.com/blogs/compute/new-amazon-ec2-spot-pricing/

And the official documentation about spot instance termination 
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-interruptions.html

You can still get outbid and lose them all if you are very aggressive with the bid price but if you bid the on demand price your instance will be terminated by out of capacity reasons way before the price reaches anywhere near the on demand price.

The out of capacity terminations are done across the entire spot capacity of all spot users in the given AZ so for a given user having multiple instances the instances will appear to be terminated randomly, not all at once like before.

There was a blog post by someone who tested it in practice and showed that the higher bid price doesn't help you keep the capacity but I can't find it anymore.

**Comment by waynerobinson** [comment]
Awesome… thanks for the clarification and the links! 👍
