### ISSUE TITLE
Failed spot instance attachment due to ASG maximum size

### ISSUE THREAD

**Issue by salvianreynaldi** [AutoSpotting/AutoSpotting#428]
According to [Attach EC2 Instances to Your Auto Scaling Group](https://docs.aws.amazon.com/autoscaling/ec2/userguide/attach-instance-asg.html),

> If the number of instances being attached plus the desired capacity exceeds the maximum size of the group, the request fails.

Meanwhile AutoSpotting currently only adds max capacity when minSize==maxSize:
https://github.com/AutoSpotting/AutoSpotting/blob/a37aafcf4382a51cbfdfbf60e7962475289c5eff/core/autoscaling.go#L230-L234

Therefore,  if ASG size params are {min:1, max:1, desired:1}, spot instances attachment will fail with this error message:
```autoscaling.go:444: ValidationError: AutoScalingGroup <asg name> has min-size=1, max-size=1, and desired-size=1. To attach 1 instance, please update the AutoScalingGroup sizes appropriately.```

Probably we should check whether `desiredCapacity == maxSize`

**Comment by cristim** [comment]
Thanks for reporting this.

I'm not sure what happened, but this shouldn't be needed/happening.

When min != max we should be able to do the swap without increasing the max by swapping the instances in the correct attach/detach order so that we're always within the boundaries of the group's capacity limits.

**Comment by salvianreynaldi** [comment]
Hi @cristim,

I see, the block below should prevent this from happening if {min:1, max:1, desired:1}
https://github.com/AutoSpotting/AutoSpotting/blob/a37aafcf4382a51cbfdfbf60e7962475289c5eff/core/autoscaling.go#L258-L275

However, I removed the if in L259 in my fork, because there was another error. Let's say the ASG size params are {min:0, max:2, desired:2}. The instances are in AZ apse1a (1) and apse1b (1).
```
Considering <a> for attaching to <asg_x>
Found spot instance: <a> Attaching it to <asg_x>
Retrieving instance details for <a>
// ...
found on-demand instance <a_od> replacing with new spot instance <a>
Terminating instance: <a_od>
<next autospotting execution, after 5 m. However, ASG desired capacity is now 1 because of instance termination>
Considering <a> for attaching to <asg_x>
Found spot instance: <a> Attaching it to <asg_x>
Retrieving instance details for <a>
// ...
<a> is in the availability zone ap-southeast-1a looking for an on-demand instance there
found no on-demand instances that could be replaced with the new spot instance <a> terminating the spot instance.
```

This is what I learn from the log:
1. A new spot instance is launched to replace the apse1a instance.
2. The 1a on-demand instance is terminated. However, the deferred attachment process failed.
3. In the next execution, asg desired is 1, and no instance is in 1a.
I think this is not a desirable situation

May I know why the attach/detach order is only reverted when running on minimum capacity?

**Comment by cristim** [comment]
I'm not sure I understand, please correct me if I'm wrong:

1.  you have an ASG with 2 instances in 2 AZs
2. one of them was cloned with spot but the spot instance was not yet swapped, awaiting next run for this
3. the on-demand instance that was cloned was terminated by the ASG scaling in, which reduced the desired capacity to 1 

In this case attaching the spot instance after the on demand instance was terminated would result in increasing the capacity of the group from 1 to 2. To avoid that we also terminate the spot instance, since the swap can no longer be completed.

The attach/detach is only reverted on minimum capacity because we can't detach an instance when at min capacity, but you can detach it at max.

Now that you mention it we could definitely do the opposite: always do attach/detach, even when at maximum capacity, when in addition we just extend the max temporarily and bring it back afterwards with a defer after the swap is done.

What do you think?

**Comment by salvianreynaldi** [comment]
[1] and [2] are correct.
> 3. the on-demand instance that was cloned was terminated by the ASG scaling in, which reduced the desired capacity to 1

The on-demand instance was terminated by AutoSpotting, not by a scale in. I guess it's because
`a.terminateInstanceInAutoScalingGroup(odInst.InstanceId)` (line 274) is executed before `defer a.attachSpotInstance(spotInstanceID)` (line 267), so the on-demand instance will be terminated even if the spot instance isn't successfully attached

I think "always attach-detach" would prevent this kind of issue from happening, it might be a safer way to replace on-demand instances
Thanks!

**Comment by salvianreynaldi** [comment]
Thanks for considering my proposal
How should we go with this? May I submit a PR for this issue?

**Comment by cristim** [comment]
I understand now, thanks for your explanation.

By all means, I'd love to see a PR for this.

**Comment by mello7tre** [comment]
Just to let you know that this problem do not happen in event based branch.
The whole logic has been changed.
